name: Build and Run Docker Container
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: docker build -t app-contenedor .
      
      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 --name app-test app-contenedor
          sleep 10
          docker ps
          docker logs app-test
      
      - name: Stop and remove container
        run: |
          docker stop app-test
          docker rm app-test
